/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ken.mizoguch.webviewer.gits;

import javafx.scene.control.Alert;
import javafx.scene.control.TextArea;

/**
 *
 * @author mizoguch-ken
 */
public class Licenses {

    private final String LICENSES
            = "*** Third Party Licenses ***\n"
            + "\n"
            + "* Gson\n"
            + "Copyright 2008 Google Inc.\n"
            + "\n"
            + "Licensed under the Apache License, Version 2.0 (the \"License\");\n"
            + "you may not use this file except in compliance with the License.\n"
            + "You may obtain a copy of the License at\n"
            + "\n"
            + "    http://www.apache.org/licenses/LICENSE-2.0\n"
            + "\n"
            + "Unless required by applicable law or agreed to in writing, software\n"
            + "distributed under the License is distributed on an \"AS IS\" BASIS,\n"
            + "WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
            + "See the License for the specific language governing permissions and\n"
            + "limitations under the License.\n"
            + "\n"
            + "\n"
            + "* JGit Core\n"
            + "This program and the accompanying materials are made available\n"
            + "under the terms of the Eclipse Distribution License v1.0 which\n"
            + "accompanies this distribution, is reproduced below, and is\n"
            + "available at http://www.eclipse.org/org/documents/edl-v10.php\n"
            + "\n"
            + "All rights reserved.\n"
            + "\n"
            + "Redistribution and use in source and binary forms, with or\n"
            + "without modification, are permitted provided that the following\n"
            + "conditions are met:\n"
            + "\n"
            + "- Redistributions of source code must retain the above copyright\n"
            + "  notice, this list of conditions and the following disclaimer.\n"
            + "\n"
            + "- Redistributions in binary form must reproduce the above\n"
            + "  copyright notice, this list of conditions and the following\n"
            + "  disclaimer in the documentation and/or other materials provided\n"
            + "  with the distribution.\n"
            + "\n"
            + "- Neither the name of the Eclipse Foundation, Inc. nor the\n"
            + "  names of its contributors may be used to endorse or promote\n"
            + "  products derived from this software without specific prior\n"
            + "  written permission.\n"
            + "\n"
            + "THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND\n"
            + "CONTRIBUTORS \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES,\n"
            + "INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES\n"
            + "OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE\n"
            + "ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR\n"
            + "CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\n"
            + "SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT\n"
            + "NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\n"
            + "LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER\n"
            + "CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,\n"
            + "STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)\n"
            + "ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF\n"
            + "ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
            + "\n"
            + "\n"
            + "* JavaEWAH\n"
            + "Apache License\n"
            + "Version 2.0, January 2004\n"
            + "http://www.apache.org/licenses/\n"
            + "\n"
            + "TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION\n"
            + "\n"
            + "1. Definitions.\n"
            + "\n"
            + "\"License\" shall mean the terms and conditions for use, reproduction, and\n"
            + "distribution as defined by Sections 1 through 9 of this document.\n"
            + "\n"
            + "\"Licensor\" shall mean the copyright owner or entity authorized by the copyright\n"
            + "owner that is granting the License.\n"
            + "\n"
            + "\"Legal Entity\" shall mean the union of the acting entity and all other entities\n"
            + "that control, are controlled by, or are under common control with that entity.\n"
            + "For the purposes of this definition, \"control\" means (i) the power, direct or\n"
            + "indirect, to cause the direction or management of such entity, whether by\n"
            + "contract or otherwise, or (ii) ownership of fifty percent (50%) or more of the\n"
            + "outstanding shares, or (iii) beneficial ownership of such entity.\n"
            + "\n"
            + "\"You\" (or \"Your\") shall mean an individual or Legal Entity exercising\n"
            + "permissions granted by this License.\n"
            + "\n"
            + "\"Source\" form shall mean the preferred form for making modifications, including\n"
            + "but not limited to software source code, documentation source, and configuration\n"
            + "files.\n"
            + "\n"
            + "\"Object\" form shall mean any form resulting from mechanical transformation or\n"
            + "translation of a Source form, including but not limited to compiled object code,\n"
            + "generated documentation, and conversions to other media types.\n"
            + "\n"
            + "\"Work\" shall mean the work of authorship, whether in Source or Object form, made\n"
            + "available under the License, as indicated by a copyright notice that is included\n"
            + "in or attached to the work (an example is provided in the Appendix below).\n"
            + "\n"
            + "\"Derivative Works\" shall mean any work, whether in Source or Object form, that\n"
            + "is based on (or derived from) the Work and for which the editorial revisions,\n"
            + "annotations, elaborations, or other modifications represent, as a whole, an\n"
            + "original work of authorship. For the purposes of this License, Derivative Works\n"
            + "shall not include works that remain separable from, or merely link (or bind by\n"
            + "name) to the interfaces of, the Work and Derivative Works thereof.\n"
            + "\n"
            + "\"Contribution\" shall mean any work of authorship, including the original version\n"
            + "of the Work and any modifications or additions to that Work or Derivative Works\n"
            + "thereof, that is intentionally submitted to Licensor for inclusion in the Work\n"
            + "by the copyright owner or by an individual or Legal Entity authorized to submit\n"
            + "on behalf of the copyright owner. For the purposes of this definition,\n"
            + "\"submitted\" means any form of electronic, verbal, or written communication sent\n"
            + "to the Licensor or its representatives, including but not limited to\n"
            + "communication on electronic mailing lists, source code control systems, and\n"
            + "issue tracking systems that are managed by, or on behalf of, the Licensor for\n"
            + "the purpose of discussing and improving the Work, but excluding communication\n"
            + "that is conspicuously marked or otherwise designated in writing by the copyright\n"
            + "owner as \"Not a Contribution.\"\n"
            + "\n"
            + "\"Contributor\" shall mean Licensor and any individual or Legal Entity on behalf\n"
            + "of whom a Contribution has been received by Licensor and subsequently\n"
            + "incorporated within the Work.\n"
            + "\n"
            + "2. Grant of Copyright License.\n"
            + "\n"
            + "Subject to the terms and conditions of this License, each Contributor hereby\n"
            + "grants to You a perpetual, worldwide, non-exclusive, no-charge, royalty-free,\n"
            + "irrevocable copyright license to reproduce, prepare Derivative Works of,\n"
            + "publicly display, publicly perform, sublicense, and distribute the Work and such\n"
            + "Derivative Works in Source or Object form.\n"
            + "\n"
            + "3. Grant of Patent License.\n"
            + "\n"
            + "Subject to the terms and conditions of this License, each Contributor hereby\n"
            + "grants to You a perpetual, worldwide, non-exclusive, no-charge, royalty-free,\n"
            + "irrevocable (except as stated in this section) patent license to make, have\n"
            + "made, use, offer to sell, sell, import, and otherwise transfer the Work, where\n"
            + "such license applies only to those patent claims licensable by such Contributor\n"
            + "that are necessarily infringed by their Contribution(s) alone or by combination\n"
            + "of their Contribution(s) with the Work to which such Contribution(s) was\n"
            + "submitted. If You institute patent litigation against any entity (including a\n"
            + "cross-claim or counterclaim in a lawsuit) alleging that the Work or a\n"
            + "Contribution incorporated within the Work constitutes direct or contributory\n"
            + "patent infringement, then any patent licenses granted to You under this License\n"
            + "for that Work shall terminate as of the date such litigation is filed.\n"
            + "\n"
            + "4. Redistribution.\n"
            + "\n"
            + "You may reproduce and distribute copies of the Work or Derivative Works thereof\n"
            + "in any medium, with or without modifications, and in Source or Object form,\n"
            + "provided that You meet the following conditions:\n"
            + "\n"
            + "You must give any other recipients of the Work or Derivative Works a copy of\n"
            + "this License; and\n"
            + "You must cause any modified files to carry prominent notices stating that You\n"
            + "changed the files; and\n"
            + "You must retain, in the Source form of any Derivative Works that You distribute,\n"
            + "all copyright, patent, trademark, and attribution notices from the Source form\n"
            + "of the Work, excluding those notices that do not pertain to any part of the\n"
            + "Derivative Works; and\n"
            + "If the Work includes a \"NOTICE\" text file as part of its distribution, then any\n"
            + "Derivative Works that You distribute must include a readable copy of the\n"
            + "attribution notices contained within such NOTICE file, excluding those notices\n"
            + "that do not pertain to any part of the Derivative Works, in at least one of the\n"
            + "following places: within a NOTICE text file distributed as part of the\n"
            + "Derivative Works; within the Source form or documentation, if provided along\n"
            + "with the Derivative Works; or, within a display generated by the Derivative\n"
            + "Works, if and wherever such third-party notices normally appear. The contents of\n"
            + "the NOTICE file are for informational purposes only and do not modify the\n"
            + "License. You may add Your own attribution notices within Derivative Works that\n"
            + "You distribute, alongside or as an addendum to the NOTICE text from the Work,\n"
            + "provided that such additional attribution notices cannot be construed as\n"
            + "modifying the License.\n"
            + "You may add Your own copyright statement to Your modifications and may provide\n"
            + "additional or different license terms and conditions for use, reproduction, or\n"
            + "distribution of Your modifications, or for any such Derivative Works as a whole,\n"
            + "provided Your use, reproduction, and distribution of the Work otherwise complies\n"
            + "with the conditions stated in this License.\n"
            + "\n"
            + "5. Submission of Contributions.\n"
            + "\n"
            + "Unless You explicitly state otherwise, any Contribution intentionally submitted\n"
            + "for inclusion in the Work by You to the Licensor shall be under the terms and\n"
            + "conditions of this License, without any additional terms or conditions.\n"
            + "Notwithstanding the above, nothing herein shall supersede or modify the terms of\n"
            + "any separate license agreement you may have executed with Licensor regarding\n"
            + "such Contributions.\n"
            + "\n"
            + "6. Trademarks.\n"
            + "\n"
            + "This License does not grant permission to use the trade names, trademarks,\n"
            + "service marks, or product names of the Licensor, except as required for\n"
            + "reasonable and customary use in describing the origin of the Work and\n"
            + "reproducing the content of the NOTICE file.\n"
            + "\n"
            + "7. Disclaimer of Warranty.\n"
            + "\n"
            + "Unless required by applicable law or agreed to in writing, Licensor provides the\n"
            + "Work (and each Contributor provides its Contributions) on an \"AS IS\" BASIS,\n"
            + "WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied,\n"
            + "including, without limitation, any warranties or conditions of TITLE,\n"
            + "NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A PARTICULAR PURPOSE. You are\n"
            + "solely responsible for determining the appropriateness of using or\n"
            + "redistributing the Work and assume any risks associated with Your exercise of\n"
            + "permissions under this License.\n"
            + "\n"
            + "8. Limitation of Liability.\n"
            + "\n"
            + "In no event and under no legal theory, whether in tort (including negligence),\n"
            + "contract, or otherwise, unless required by applicable law (such as deliberate\n"
            + "and grossly negligent acts) or agreed to in writing, shall any Contributor be\n"
            + "liable to You for damages, including any direct, indirect, special, incidental,\n"
            + "or consequential damages of any character arising as a result of this License or\n"
            + "out of the use or inability to use the Work (including but not limited to\n"
            + "damages for loss of goodwill, work stoppage, computer failure or malfunction, or\n"
            + "any and all other commercial damages or losses), even if such Contributor has\n"
            + "been advised of the possibility of such damages.\n"
            + "\n"
            + "9. Accepting Warranty or Additional Liability.\n"
            + "\n"
            + "While redistributing the Work or Derivative Works thereof, You may choose to\n"
            + "offer, and charge a fee for, acceptance of support, warranty, indemnity, or\n"
            + "other liability obligations and/or rights consistent with this License. However,\n"
            + "in accepting such obligations, You may act only on Your own behalf and on Your\n"
            + "sole responsibility, not on behalf of any other Contributor, and only if You\n"
            + "agree to indemnify, defend, and hold each Contributor harmless for any liability\n"
            + "incurred by, or claims asserted against, such Contributor by reason of your\n"
            + "accepting any such warranty or additional liability.\n"
            + "\n"
            + "END OF TERMS AND CONDITIONS\n"
            + "\n"
            + "APPENDIX: How to apply the Apache License to your work\n"
            + "\n"
            + "To apply the Apache License to your work, attach the following boilerplate\n"
            + "notice, with the fields enclosed by brackets \"[]\" replaced with your own\n"
            + "identifying information. (Don't include the brackets!) The text should be\n"
            + "enclosed in the appropriate comment syntax for the file format. We also\n"
            + "recommend that a file or class name and description of purpose be included on\n"
            + "the same \"printed page\" as the copyright notice for easier identification within\n"
            + "third-party archives.\n"
            + "\n"
            + "(c) 2009-2016 Daniel Lemire (http://lemire.me/en/), Cliff Moon, David McIntosh (https://github.com/mctofu), Robert Becho (https://github.com/RBecho), Colby Ranger (https://github.com/crangeratgoogle), Veronika Zenz (https://github.com/veronikazenz), Owen Kaser (https://github.com/owenkaser), Gregory Ssi-Yan-Kai (https://github.com/gssiyankai), and Rory Graves (https://github.com/rorygraves)\n"
            + "\n"
            + "   Licensed under the Apache License, Version 2.0 (the \"License\");\n"
            + "   you may not use this file except in compliance with the License.\n"
            + "   You may obtain a copy of the License at\n"
            + "\n"
            + "     http://www.apache.org/licenses/LICENSE-2.0\n"
            + "\n"
            + "   Unless required by applicable law or agreed to in writing, software\n"
            + "   distributed under the License is distributed on an \"AS IS\" BASIS,\n"
            + "   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
            + "   See the License for the specific language governing permissions and\n"
            + "   limitations under the License.\n"
            + "\n"
            + "\n"
            + "* Apache Commons Codec\n"
            + "Copyright 2002-2016 The Apache Software Foundation\n"
            + "\n"
            + "Licensed under the Apache License, Version 2.0 (the \"License\");\n"
            + "you may not use this file except in compliance with the License.\n"
            + "You may obtain a copy of the License at\n"
            + "\n"
            + "    http://www.apache.org/licenses/LICENSE-2.0\n"
            + "\n"
            + "Unless required by applicable law or agreed to in writing, software\n"
            + "distributed under the License is distributed on an \"AS IS\" BASIS,\n"
            + "WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
            + "See the License for the specific language governing permissions and\n"
            + "limitations under the License.\n"
            + "\n"
            + "This product includes software developed at\n"
            + "The Apache Software Foundation (http://www.apache.org/).\n"
            + "\n"
            + "src/test/org/apache/commons/codec/language/DoubleMetaphoneTest.java\n"
            + "contains test data from http://aspell.net/test/orig/batch0.tab.\n"
            + "Copyright (C) 2002 Kevin Atkinson (kevina@gnu.org)\n"
            + "\n"
            + "===============================================================================\n"
            + "\n"
            + "The content of package org.apache.commons.codec.language.bm has been translated\n"
            + "from the original php source code available at http://stevemorse.org/phoneticinfo.htm\n"
            + "with permission from the original authors.\n"
            + "Original source copyright:\n"
            + "Copyright (c) 2008 Alexander Beider & Stephen P. Morse.\n"
            + "\n"
            + "\n"
            + "* Apache Commons Logging\n"
            + "Copyright 2003-2016 The Apache Software Foundation\n"
            + "\n"
            + "Licensed under the Apache License, Version 2.0 (the \"License\");\n"
            + "you may not use this file except in compliance with the License.\n"
            + "You may obtain a copy of the License at\n"
            + "\n"
            + "    http://www.apache.org/licenses/LICENSE-2.0\n"
            + "\n"
            + "Unless required by applicable law or agreed to in writing, software\n"
            + "distributed under the License is distributed on an \"AS IS\" BASIS,\n"
            + "WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
            + "See the License for the specific language governing permissions and\n"
            + "limitations under the License.\n"
            + "\n"
            + "This product includes software developed at\n"
            + "The Apache Software Foundation (http://www.apache.org/).\n"
            + "\n"
            + "\n"
            + "* Apache HttpClient\n"
            + "Copyright 1999-2017 The Apache Software Foundation\n"
            + "\n"
            + "Licensed under the Apache License, Version 2.0 (the \"License\");\n"
            + "you may not use this file except in compliance with the License.\n"
            + "You may obtain a copy of the License at\n"
            + "\n"
            + "    http://www.apache.org/licenses/LICENSE-2.0\n"
            + "\n"
            + "Unless required by applicable law or agreed to in writing, software\n"
            + "distributed under the License is distributed on an \"AS IS\" BASIS,\n"
            + "WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
            + "See the License for the specific language governing permissions and\n"
            + "limitations under the License.\n"
            + "\n"
            + "This product includes software developed at\n"
            + "The Apache Software Foundation (http://www.apache.org/).\n"
            + "\n"
            + "\n"
            + "* Apache HttpCore\n"
            + "Copyright 2005-2017 The Apache Software Foundation\n"
            + "\n"
            + "Licensed under the Apache License, Version 2.0 (the \"License\");\n"
            + "you may not use this file except in compliance with the License.\n"
            + "You may obtain a copy of the License at\n"
            + "\n"
            + "    http://www.apache.org/licenses/LICENSE-2.0\n"
            + "\n"
            + "Unless required by applicable law or agreed to in writing, software\n"
            + "distributed under the License is distributed on an \"AS IS\" BASIS,\n"
            + "WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
            + "See the License for the specific language governing permissions and\n"
            + "limitations under the License.\n"
            + "\n"
            + "This product includes software developed at\n"
            + "The Apache Software Foundation (http://www.apache.org/).\n"
            + "\n"
            + "\n"
            + "* JSch\n"
            + "JSch 0.0.* was released under the GNU LGPL license.  Later, we have switched \n"
            + "over to a BSD-style license. \n"
            + "\n"
            + "------------------------------------------------------------------------------\n"
            + "Copyright (c) 2002-2010 Atsuhiko Yamanaka, JCraft,Inc. \n"
            + "All rights reserved.\n"
            + "\n"
            + "Redistribution and use in source and binary forms, with or without\n"
            + "modification, are permitted provided that the following conditions are met:\n"
            + "\n"
            + "  1. Redistributions of source code must retain the above copyright notice,\n"
            + "     this list of conditions and the following disclaimer.\n"
            + "\n"
            + "  2. Redistributions in binary form must reproduce the above copyright \n"
            + "     notice, this list of conditions and the following disclaimer in \n"
            + "     the documentation and/or other materials provided with the distribution.\n"
            + "\n"
            + "  3. The names of the authors may not be used to endorse or promote products\n"
            + "     derived from this software without specific prior written permission.\n"
            + "\n"
            + "THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED WARRANTIES,\n"
            + "INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND\n"
            + "FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL JCRAFT,\n"
            + "INC. OR ANY CONTRIBUTORS TO THIS SOFTWARE BE LIABLE FOR ANY DIRECT, INDIRECT,\n"
            + "INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\n"
            + "LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,\n"
            + "OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF\n"
            + "LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING\n"
            + "NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,\n"
            + "EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
            + "\n"
            + "\n"
            + "* SLF4J API Module\n"
            + "Copyright (c) 2004-2017 QOS.ch\n"
            + "All rights reserved.\n"
            + "\n"
            + "Permission is hereby granted, free  of charge, to any person obtaining\n"
            + "a  copy  of this  software  and  associated  documentation files  (the\n"
            + "\"Software\"), to  deal in  the Software without  restriction, including\n"
            + "without limitation  the rights to  use, copy, modify,  merge, publish,\n"
            + "distribute,  sublicense, and/or sell  copies of  the Software,  and to\n"
            + "permit persons to whom the Software  is furnished to do so, subject to\n"
            + "the following conditions:\n"
            + "\n"
            + "The  above  copyright  notice  and  this permission  notice  shall  be\n"
            + "included in all copies or substantial portions of the Software.\n"
            + "\n"
            + "THE  SOFTWARE IS  PROVIDED  \"AS  IS\", WITHOUT  WARRANTY  OF ANY  KIND,\n"
            + "EXPRESS OR  IMPLIED, INCLUDING  BUT NOT LIMITED  TO THE  WARRANTIES OF\n"
            + "MERCHANTABILITY,    FITNESS    FOR    A   PARTICULAR    PURPOSE    AND\n"
            + "NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE\n"
            + "LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION\n"
            + "OF CONTRACT, TORT OR OTHERWISE,  ARISING FROM, OUT OF OR IN CONNECTION\n"
            + "WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.";

    public void show() {
        Alert alert = new Alert(Alert.AlertType.INFORMATION);
        TextArea textAera = new TextArea();

        textAera.setText(LICENSES);
        alert.setResizable(true);
        alert.setTitle("Licenses");
        alert.getDialogPane().setHeaderText(null);
        textAera.setEditable(false);
        textAera.setWrapText(true);
        alert.getDialogPane().setContent(textAera);
        alert.show();
    }
}
